### ISSUE TITLE
AdaptiveDatePicker is always black on iOS when shown in a bottom sheet

### ISSUE THREAD

**Issue by ZacSweers** [MohamedRejeb/Calf#115]
Not exactly sure what to look for but I do see some logs that seem to suggest iOS isn't happy with the bounds?

![image](https://github.com/user-attachments/assets/1f328d3d-b1d4-40e1-88e7-bb3024082d42)

<img width="897" alt="IMG_6467" src="https://github.com/user-attachments/assets/e66139e8-8cb1-482b-b7c1-c966fa6a9135">

Code: https://github.com/ZacSweers/FieldSpottr/pull/26/files#diff-c263ba207ac064a923571e58dd0ae4ee321a6a3b900cfd64b2974647903dfd0fR65-R73
Repro: https://github.com/ZacSweers/FieldSpottr/pull/26

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue.
The problem is that I'm creating a new `UIViewController` for the `AdaptiveBottomSheet` and I'm passing `currentCompositionLocalContext` to the bottom sheet content, but this also overrides the new `UIViewController` with the old one, so the `AdaptiveDatePicker` gets drawn on the wrong view behind the bottom sheet.

**Comment by MohamedRejeb** [comment]
I have released a new version `0.5.2` with the fix.

**Comment by ZacSweers** [comment]
Thanks! Will try it out today

**Comment by ZacSweers** [comment]
Works like a charm! Although, it seems to not work with dark mode but maybe that's a separate issue due to the sheet always presenting in light mode?

![image](https://github.com/user-attachments/assets/64f08922-7fc4-4cc3-a73a-e66e724aea8b)
