### ISSUE TITLE
UIDatePicker is always in UTC time

### ISSUE THREAD

**Issue by ZacSweers** [MohamedRejeb/Calf#172]
When showing an `AdaptiveDatePicker` on iOS, the date picker always shows in UTC time regardless of the local timezone. This results in the "current day" sometimes being off. For example - I am in new york city time writing this at 10pm sunday evening, but if I look at the date picker right now it believes the current day is tomorrow - monday sept 2nd.

**Comment by MohamedRejeb** [comment]
Thanks for reporting this. I will check it.

**Comment by MohamedRejeb** [comment]
Hi Zac,
Are you facing this issue with material3 DatePicker as well? Because material3 DatePicker always shows in UTC time as well which is confusing.

https://github.com/JetBrains/compose-multiplatform-core/blob/91f4fb52bb54a655fe72c71623e166c52b2bbaa2/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/DatePicker.kt#L1159

https://github.com/JetBrains/compose-multiplatform-core/blob/91f4fb52bb54a655fe72c71623e166c52b2bbaa2/compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/internal/KotlinxDatetimeCalendarModel.kt#L66

**Comment by ZacSweers** [comment]
Sorry for the delay. I do believe this is working fine on android

**Comment by MohamedRejeb** [comment]
Ah ok, I thought that you were talking about the selected date not the current date.
I'm working on it.

**Comment by MohamedRejeb** [comment]
It should be working fine now. I've published a new version `0.6.1` with the fix.
